variables:
  ODOO_TEST_URL:
    source: ODOO_TEST_URL
    type: str
  ODOO_TEST_DB:
    source: ODOO_TEST_DB
    type: str
  ODOO_TEST_USERNAME:
    source: ODOO_TEST_USERNAME
    type: str
  ODOO_TEST_PASSWORD:
    source: ODOO_TEST_PASSWORD
    type: str

  OPENAI_API_KEY:
    source: OPENAI_API_KEY
    type: str
  LLM_MODEL:
    source: LLM_MODEL
    type: str
    default: "gpt-4o-mini"

  SLACK_APP_TOKEN:
    source: INVOICE_SLACK_APP_TOKEN
    type: str
  SLACK_BOT_TOKEN:
    source: INVOICE_SLACK_BOT_TOKEN
    type: str

  SLACK_DEBUG_LOGS:
    source: SLACK_DEBUG_LOGS
    type: bool
    default: false

  DATA_PATH:
    source: DATA_PATH
    type: str
    default: /Users/bastianibanez/work/invoice-processor/data

validation:
  required:
    - ODOO_TEST_URL
    - ODOO_TEST_DB
    - ODOO_TEST_USERNAME
    - ODOO_TEST_PASSWORD
    - OPENAI_API_KEY
    - SLACK_APP_TOKEN
    - SLACK_BOT_TOKEN
    - DATA_PATH
  optional:
    - LLM_MODEL
    - SLACK_DEBUG_LOGS
  strict: false
